<<<<<<< HEAD
title: MyTitle
name: MySiteName
description: MyDescription
author: Me
lang: en
baseurl: ""
markdown: kramdown
=======
url: http://psconf.eu
baseurl: ""
title: PowerShell Conference EU

gems:
  - octopress-multilingual
lang: en

# Build settings
markdown: kramdown
permalink: pretty

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333
>>>>>>> origin/master
